POST http://localhost:3000/signup
Content-Type: application/json

{
  "name":"erick",
  "email":"erick@mail.com",
  "password":"erickreidelas"
}

###
POST http://localhost:3000/signin
Content-Type: application/json

{
  "email":"erick@mail.com",
  "password":"erickreidelas"
}
# {
#   "email":"vitao@mail.com",
#   "password":"vitao123reidelas"
# }

###
GET http://localhost:3000/leads
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZXJpY2siLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc0NTI5MDY3NSwiZXhwIjoxNzQ1Mzc3MDc1LCJzdWIiOiJlYWRmMzdkMy04MWFjLTRhMzEtYTliNi1lNzRlYTgzMDNiMWEifQ.pIr3u09OpIecfoSI1YCkClj53NfA_i1InaUjH0RIXBs

###
POST http://localhost:3000/leads
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZXJpY2siLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NDUyOTI0MzMsImV4cCI6MTc0NTM3ODgzMywic3ViIjoiZWFkZjM3ZDMtODFhYy00YTMxLWE5YjYtZTc0ZWE4MzAzYjFhIn0.w7UEyVbeqJ0pX73ueu9VyT5phOkzEwDEQVZ2OfkdY4s
